#micronaut:
#  data:
#    jpa:
#      packages: 'com.example.entity'
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#datasources:
#  default:
#    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#    username: ${JDBC_USER:sa}
#    password: ${JDBC_PASSWORD:""}
#    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    dialect: H2

micronaut:
  h2:
    console:
      enabled: true
      path: /h2

jpa:
  default:
    entity-scan:
      packages: 'com.example.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true