openapi: 3.0.1
info:
  title: demo
  version: "0.0"
paths:
  /card:
    get:
      operationId: index
      responses:
        "200":
          description: index 200 response
          content:
            text/plain:
              schema:
                type: string
  /payments:
    post:
      operationId: postPaymentRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
        required: true
      responses:
        "200":
          description: postPaymentRequest 200 response
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Origin:
      type: object
      properties:
        name:
          type: string
        cpf:
          type: string
    PaymentRequest:
      type: object
      properties:
        origin:
          $ref: '#/components/schemas/Origin'
        paymentType:
          $ref: '#/components/schemas/PaymentType'
        amount:
          type: number
        requestDate:
          type: string
          format: date-time
    PaymentType:
      type: string
      enum:
      - CREDIT_CARD
      - DEBIT_CARD
      - BANK_ACCOUNT
